### ISSUE TITLE
Create Djando custom commands to import CSV data for articles

### ISSUE THREAD

**Issue by nilandev** [StackTipsLab/bloggy#9]
We want to create a Django Command similar to `bloggy/bloggy/management/commands/import_content.py` to import demo contents from a specific directory. 

Note that the `import_content` command calls the `import_categories` command internally. As a part of this ticket, we want to create custom commands to import articles. 

```python
 call_command('import_categories', '--file={}/categories.csv'.format(file_path))
 ```

**Comment by Lamma-maihadisi** [comment]
Please provide a description for this issue

**Comment by nilandev** [comment]
@Lamma-maihadisi updated the ticket with additional details. Hopefully this helps. 
For any questions please let me know.

**Comment by nilandev** [comment]
Articles importer added in #26.

**Comment by nilandev** [comment]
Fixed.
